# Generated by Django 4.2.14 on 2024-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedtweet",
            name="for_account",
            field=models.CharField(
                choices=[("dopeshi", "DopeShi"), ("why_trending", "Why Trending")],
                default="dopeshi",
                max_length=20,
            ),
        ),
    ]
