# Generated by Django 4.2.14 on 2024-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0002_generatedtweet_for_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedtweet",
            name="tweet_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
