# Generated by Django 4.2.14 on 2024-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0003_generatedtweet_tweet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedtweet",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
